In [2]:
import numpy as np

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [7]:
A = np.random.randn(10)

In [8]:
A

array([ 1.37359928, -0.16659203,  1.05780654,  0.22757486, -0.6083704 ,
        1.95672914, -0.42359455,  0.76635464, -0.01575391, -0.20055585])

In [9]:
B = np.random.randn(10)

In [10]:
B

array([-0.9160628 , -1.05979496,  0.0631251 , -0.01088601, -1.67024388,
       -0.1267163 ,  0.30933892,  0.59511592, -0.8953872 ,  1.25258706])

In [11]:
# Binary Functions
np.add(A, B)

array([ 0.45753649, -1.226387  ,  1.12093164,  0.21668885, -2.27861428,
        1.83001284, -0.11425564,  1.36147056, -0.91114111,  1.05203121])

In [13]:
np.maximum(A,B)

array([ 1.37359928, -0.16659203,  1.05780654,  0.22757486, -0.6083704 ,
        1.95672914,  0.30933892,  0.76635464, -0.01575391,  1.25258706])