In [2]:
import numpy as np

In [3]:
5/2

2.5

In [4]:
ar1 = np.array([[1,2,3,4],[5,6,7,8]])

In [5]:
ar1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
ar1 * ar1

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [7]:
ar1 ** 3

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]], dtype=int32)